version = 0.1
[default.deploy.parameters]
stack_name = "lakeformation-permission"
resolve_s3 = true
s3_prefix = "lakeformation-permission"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "GroupName=\"athena_query_permission\" UserName=\"user_lakeformation\""
image_repositories = []
